fn main() {
    // 1. Tell Cargo to re-run this script if any files in the data folder change.
    // This ensures that if you edit your TSVs, the .dat file is updated.
    println!("cargo:rerun-if-changed=data/");

    // Also re-run if the xtask logic itself changes.
    println!("cargo:rerun-if-changed=xtask/src/");

    // 2. Call the generation logic from your xtask crate.
    // We use the 'xtask' namespace because you added it as a build-dependency.
    if let Err(e) = xtask::build_trie_data() {
        // Using eprintln and panic ensures the error is visible in the terminal
        // if the build fails.
        eprintln!("Error: Failed to generate dictionary data: {}", e);
        std::process::exit(1);
    }

    // 3. Optional: Print a message to the build log (viewable with -vv)
    println!("cargo:warning=Dictionary trie.dat successfully generated by build.rs");
}
